(feat) use native promisify and remove es6-promisify
godaddy/terminus pull request #165
Opened 2020-12-01 15:38 UTC by rxmarbles

Remove unnecessary package as we can use native promisify. Also switched ot using `Promis.allSettled` for each of the processes in `cleanup`

2020-12-01 16:15 UTC, gergelyke requested changes

2020-12-01 16:15 UTC, gergelyke commented on lib/terminus.js
> -        await beforeShutdown()
it's imperative that these events are called in sequential order

2020-12-02 01:33 UTC, gergelyke approved these changes
thank you

2020-12-02 01:34 UTC, gergelyke commented
it seems like that your code style changes broke the TS type checks - can you look into them please?

2020-12-02 02:31 UTC, rxmarbles commented
@gergelyke Not sure what the culprit was. So I reverted pacakge.json and lock file to what is in main and then removed the `es6-promisify` via `npm unistalled` ran it locally and seems to work now.

2020-12-02 22:01 UTC, merged